# Generated by Django 4.2 on 2023-10-25 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(default=None, max_length=100)),
                ('marc_model', models.CharField(default=None, max_length=100)),
                ('serie', models.CharField(default=None, max_length=100)),
                ('estade', models.CharField(default=None, max_length=50)),
                ('observations', models.CharField(default=None, max_length=200)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'store',
            },
        ),
        migrations.CreateModel(
            name='work',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('gmail', models.CharField(default=None, max_length=50)),
                ('area', models.CharField(max_length=60)),
                ('post', models.CharField(max_length=60, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='INVENTARIO.store')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='delivery_record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_date', models.DateTimeField(auto_now_add=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INVENTARIO.work')),
            ],
            options={
                'verbose_name_plural': 'delivery_record',
            },
        ),
        migrations.CreateModel(
            name='ActaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_pdf', models.FileField(upload_to='build/actas_entrega_pdfs/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('Users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INVENTARIO.users')),
            ],
        ),
    ]
