# Generated by Django 4.2 on 2023-10-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actaentrega',
            name='archivo_pdf',
            field=models.FileField(upload_to='actas_entrega_pdfs'),
        ),
    ]
