# Generated by Django 4.2 on 2023-10-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0002_alter_actaentrega_archivo_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actaentrega',
            name='archivo_pdf',
            field=models.FileField(upload_to='actas_entrega_pdfs/'),
        ),
    ]
