# Generated by Django 4.2 on 2023-10-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0003_alter_actaentrega_archivo_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actaentrega',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
