# Generated by Django 4.2 on 2024-03-06 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0006_users_area_de_trabajo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='area_de_trabajo',
        ),
    ]
