# Generated by Django 4.2 on 2024-03-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0007_remove_users_area_de_trabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='area_de_trabajo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='codigo_de_personal',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='local',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='motivo_de_alta',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='naturaleza_de_puesto',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='nomenclatura_de_puesto',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='sub_area_de_trabajo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='tipo_de_puesto',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='ubicación_fisica',
            field=models.CharField(default='', max_length=20),
        ),
    ]
