# Generated by Django 4.2 on 2024-03-06 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0008_users_area_de_trabajo_users_codigo_de_personal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='ubicación_fisica',
            new_name='ubicacion_fisica',
        ),
    ]
