# Generated by Django 4.2 on 2024-03-06 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0009_rename_ubicación_fisica_users_ubicacion_fisica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='codigo_de_personal',
        ),
        migrations.RemoveField(
            model_name='users',
            name='local',
        ),
        migrations.RemoveField(
            model_name='users',
            name='motivo_de_alta',
        ),
        migrations.RemoveField(
            model_name='users',
            name='naturaleza_de_puesto',
        ),
        migrations.RemoveField(
            model_name='users',
            name='nomenclatura_de_puesto',
        ),
        migrations.RemoveField(
            model_name='users',
            name='sub_area_de_trabajo',
        ),
        migrations.RemoveField(
            model_name='users',
            name='tipo_de_puesto',
        ),
        migrations.RemoveField(
            model_name='users',
            name='ubicacion_fisica',
        ),
    ]
