# Generated by Django 4.2 on 2024-03-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0011_users_sub_area_de_trabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='ubicacion_fisica',
            field=models.CharField(default='', max_length=20),
        ),
    ]
