# Generated by Django 4.2 on 2024-03-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0012_users_ubicacion_fisica'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='local',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='naturaleza_de_puesto',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='nomenclatura_de_puesto',
            field=models.CharField(default='', max_length=20),
        ),
    ]
