# Generated by Django 4.2 on 2024-03-06 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0013_users_local_users_naturaleza_de_puesto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='naturaleza_de_puesto',
        ),
        migrations.RemoveField(
            model_name='users',
            name='nomenclatura_de_puesto',
        ),
    ]
