# Generated by Django 4.2 on 2024-03-06 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0014_remove_users_naturaleza_de_puesto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='local',
        ),
    ]
