# Generated by Django 4.2 on 2024-03-06 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0016_users_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='local',
        ),
    ]
