# Generated by Django 4.2 on 2024-03-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0018_users_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='naturaleza_de_puesto',
            field=models.CharField(default='', max_length=100),
        ),
    ]
