# Generated by Django 4.2 on 2024-03-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0020_users_nomenclatura_de_puesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='nomenclatura_de_puesto',
            field=models.CharField(default='', max_length=100),
        ),
    ]
