# Generated by Django 4.2 on 2024-03-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0021_alter_users_nomenclatura_de_puesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='codigo_de_personal',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='motivo_de_alta',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='tipo_de_puesto',
            field=models.CharField(default='', max_length=20),
        ),
    ]
