# Generated by Django 4.2 on 2024-03-07 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0022_users_codigo_de_personal_users_motivo_de_alta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='codigo_de_personal',
        ),
    ]
