# Generated by Django 4.2 on 2024-03-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0023_remove_users_codigo_de_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='codigo_de_personal',
            field=models.BigIntegerField(default=0),
        ),
    ]
