# Generated by Django 4.2 on 2024-03-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0024_users_codigo_de_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='apellidos_y_nombres_adryan',
            field=models.CharField(default='', max_length=100),
        ),
    ]
