# Generated by Django 4.2 on 2024-03-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0025_users_apellidos_y_nombres_adryan'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='genero_adryan',
            field=models.CharField(default='', max_length=20),
        ),
    ]
