# Generated by Django 4.2 on 2024-03-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0027_users_fecha_de_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='nacionalidad_adryan',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='tipo_de_contrato_adryan',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='tipo_de_jornada_adryan',
            field=models.CharField(default='', max_length=50),
        ),
    ]
