# Generated by Django 4.2 on 2024-03-07 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0028_users_nacionalidad_adryan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='tiempo_de_servicio_anios',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='users',
            name='tiempo_de_servicio_dias',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='users',
            name='tiempo_de_servicio_meses',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12)]),
        ),
    ]
