# Generated by Django 4.2 on 2024-03-07 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0029_users_tiempo_de_servicio_anios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='correo_corporativo_adryan',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='edad_adryan',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='users',
            name='fecha_de_nacimiento_adryan',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='users',
            name='generacion_adryan',
            field=models.CharField(default='', max_length=50),
        ),
    ]
