# Generated by Django 4.2 on 2024-03-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0030_users_correo_corporativo_adryan_users_edad_adryan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='jefe_inmediato_jerarquico',
            field=models.CharField(default='', max_length=50),
        ),
    ]
