# Generated by Django 4.2 on 2024-03-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0032_users_store_alter_users_jefe_inmediato_jerarquico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='motivo_de_alta',
            field=models.CharField(default='', max_length=100),
        ),
    ]
