# Generated by Django 4.2 on 2024-03-18 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0033_alter_users_motivo_de_alta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='apellidos_y_nombres_adryan',
        ),
        migrations.RemoveField(
            model_name='users',
            name='area_de_trabajo',
        ),
        migrations.RemoveField(
            model_name='users',
            name='codigo_de_personal',
        ),
        migrations.RemoveField(
            model_name='users',
            name='correo_corporativo_adryan',
        ),
        migrations.RemoveField(
            model_name='users',
            name='edad_adryan',
        ),
        migrations.RemoveField(
            model_name='users',
            name='fecha_de_ingreso',
        ),
        migrations.RemoveField(
            model_name='users',
            name='fecha_de_nacimiento_adryan',
        ),
        migrations.RemoveField(
            model_name='users',
            name='generacion_adryan',
        ),
        migrations.RemoveField(
            model_name='users',
            name='genero_adryan',
        ),
        migrations.RemoveField(
            model_name='users',
            name='jefe_inmediato_jerarquico',
        ),
        migrations.RemoveField(
            model_name='users',
            name='local',
        ),
        migrations.RemoveField(
            model_name='users',
            name='motivo_de_alta',
        ),
        migrations.RemoveField(
            model_name='users',
            name='nacionalidad_adryan',
        ),
        migrations.RemoveField(
            model_name='users',
            name='naturaleza_de_puesto',
        ),
        migrations.RemoveField(
            model_name='users',
            name='nomenclatura_de_puesto',
        ),
        migrations.RemoveField(
            model_name='users',
            name='planilla',
        ),
        migrations.RemoveField(
            model_name='users',
            name='reemplaza_a',
        ),
        migrations.RemoveField(
            model_name='users',
            name='sub_area_de_trabajo',
        ),
        migrations.RemoveField(
            model_name='users',
            name='tiempo_de_servicio_anios',
        ),
        migrations.RemoveField(
            model_name='users',
            name='tiempo_de_servicio_dias',
        ),
        migrations.RemoveField(
            model_name='users',
            name='tiempo_de_servicio_meses',
        ),
        migrations.RemoveField(
            model_name='users',
            name='tipo_de_contrato_adryan',
        ),
        migrations.RemoveField(
            model_name='users',
            name='tipo_de_jornada_adryan',
        ),
        migrations.RemoveField(
            model_name='users',
            name='tipo_de_puesto',
        ),
        migrations.RemoveField(
            model_name='users',
            name='ubicacion_fisica',
        ),
        migrations.RemoveField(
            model_name='users',
            name='unidad_de_negocio',
        ),
    ]
