# Generated by Django 4.2 on 2024-03-18 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0034_remove_users_apellidos_y_nombres_adryan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='apellidos_y_nombres_adryan',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='area_de_trabajo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='codigo_de_personal',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='correo_corporativo_adryan',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='edad_adryan',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='users',
            name='fecha_de_ingreso',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='users',
            name='fecha_de_nacimiento_adryan',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='users',
            name='generacion_adryan',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='genero_adryan',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='jefe_inmediato_jerarquico',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='local',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='motivo_de_alta',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='nacionalidad_adryan',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='naturaleza_de_puesto',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='nomenclatura_de_puesto',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='planilla',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='users',
            name='reemplaza_a',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='sub_area_de_trabajo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='tiempo_de_servicio_anios',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='users',
            name='tiempo_de_servicio_dias',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='users',
            name='tiempo_de_servicio_meses',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='users',
            name='tipo_de_contrato_adryan',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='tipo_de_jornada_adryan',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='tipo_de_puesto',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='ubicacion_fisica',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='unidad_de_negocio',
            field=models.CharField(default='', max_length=50),
        ),
    ]
