# Generated by Django 4.2 on 2024-03-28 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0035_users_apellidos_y_nombres_adryan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'activo',
            },
        ),
        migrations.RemoveField(
            model_name='users',
            name='store',
        ),
        migrations.DeleteModel(
            name='store',
        ),
        migrations.AddField(
            model_name='users',
            name='activo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='INVENTARIO.activo'),
        ),
    ]
