# Generated by Django 4.2 on 2024-03-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0036_activo_remove_users_store_delete_store_users_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='description',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='activo',
            name='estade',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='activo',
            name='marc_model',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='activo',
            name='observations',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='activo',
            name='serie',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
