# Generated by Django 4.2 on 2024-03-28 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0037_activo_description_activo_estade_activo_marc_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='estade',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='marc_model',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='serie',
        ),
    ]
