# Generated by Django 4.2 on 2024-03-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0039_prueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='planilla',
            field=models.CharField(default='', max_length=10),
        ),
    ]
