# Generated by Django 4.2 on 2024-03-28 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0040_activo_planilla'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activo',
            old_name='planilla',
            new_name='sede',
        ),
    ]
