# Generated by Django 4.2 on 2024-03-28 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0041_rename_planilla_activo_sede'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activo',
            name='sede',
        ),
    ]
