# Generated by Django 4.2 on 2024-03-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0042_remove_activo_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='pabellon',
            field=models.CharField(default='', max_length=5),
        ),
    ]
