# Generated by Django 4.2 on 2024-03-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0043_activo_pabellon'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='ambiente',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='activo',
            name='categoria',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='activo',
            name='codigo_inventario',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='activo',
            name='contrato',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='activo',
            name='descripcion',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='activo',
            name='devolucion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='activo',
            name='direccion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='activo',
            name='distrito',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='activo',
            name='estado',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='activo',
            name='estado_renta',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='activo',
            name='fecha_registro',
            field=models.DateTimeField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='activo',
            name='hostname',
            field=models.CharField(default='hs', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='activo',
            name='marca',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='activo',
            name='modelo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='activo',
            name='proveedor',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='activo',
            name='renta',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='activo',
            name='sede',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='activo',
            name='serie',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='activo',
            name='tipo_ambiente',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='activo',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
