# Generated by Django 4.2 on 2024-03-28 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0044_activo_ambiente_activo_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activo',
            name='ambiente',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='codigo_inventario',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='contrato',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='devolucion',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='distrito',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='estado_renta',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='hostname',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='pabellon',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='renta',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='sede',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='serie',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='tipo_ambiente',
        ),
    ]
