# Generated by Django 4.2 on 2024-03-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0045_remove_activo_ambiente_remove_activo_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='sede',
            field=models.CharField(default='', max_length=50),
        ),
    ]
