# Generated by Django 4.2 on 2024-03-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0049_activo_tipo_ambiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='ambiente',
            field=models.CharField(default='', max_length=100),
        ),
    ]
