# Generated by Django 4.2 on 2024-03-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0053_activo_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='codigo_inventario',
            field=models.CharField(default='', max_length=50),
        ),
    ]
