# Generated by Django 4.2 on 2024-03-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0056_activo_descripcion_activo_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='hostname',
            field=models.CharField(default='hs', max_length=50, null=True),
        ),
    ]
