# Generated by Django 4.2 on 2024-03-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0057_activo_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='estado',
            field=models.CharField(default='', max_length=50),
        ),
    ]
