# Generated by Django 4.2 on 2024-03-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0061_activo_estado_renta'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='proveedor',
            field=models.CharField(default='', max_length=50),
        ),
    ]
