# Generated by Django 4.2 on 2024-03-28 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0064_activo_fecha_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activo',
            name='fecha_registro',
        ),
    ]
