# Generated by Django 4.2 on 2024-03-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0065_remove_activo_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='campus',
            field=models.TextField(default='', max_length=20),
        ),
    ]
