# Generated by Django 4.2 on 2024-03-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0066_activo_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='campus',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='activo',
            name='descripcion',
            field=models.TextField(default=''),
        ),
    ]
