# Generated by Django 4.2 on 2024-04-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0067_alter_activo_campus_alter_activo_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activo',
            name='campus',
        ),
        migrations.AlterField(
            model_name='activo',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
