# Generated by Django 4.2 on 2024-04-09 18:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0070_delete_prueba_activo_asignado_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='fecha_asignacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
