# Generated by Django 4.2 on 2024-04-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0071_activo_fecha_asignacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='fecha_asignacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
