# Generated by Django 4.2 on 2024-04-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0072_alter_activo_fecha_asignacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='fecha_asignacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
