# Generated by Django 4.2 on 2024-04-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0073_alter_activo_fecha_asignacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actaentrega',
            old_name='Users',
            new_name='usuarios',
        ),
        migrations.AlterField(
            model_name='activo',
            name='fecha_asignacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
