# Generated by Django 4.2 on 2024-04-14 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0076_rename_usuarios_actaentrega_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionActivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INVENTARIO.activo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INVENTARIO.user')),
            ],
            options={
                'verbose_name': 'Asignación de Activo',
                'verbose_name_plural': 'Asignaciones de Activos',
            },
        ),
    ]
