# Generated by Django 4.2 on 2024-04-15 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0077_asignacionactivo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='asignacionactivo',
            table='AsignacionActivo',
        ),
    ]
