# Generated by Django 4.2 on 2024-04-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0079_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionactivo',
            name='fecha_devolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
