# Generated by Django 4.2 on 2024-04-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0080_asignacionactivo_fecha_devolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='declaracion',
            field=models.CharField(default='', max_length=20),
        ),
    ]
