# Generated by Django 4.2 on 2024-04-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0081_activo_declaracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='declaracion',
            field=models.CharField(default='ACTIVO', max_length=20),
        ),
    ]
