# Generated by Django 4.2 on 2024-04-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0082_alter_activo_declaracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionactivo',
            name='devuelto',
            field=models.BooleanField(default=False),
        ),
    ]
