# Generated by Django 4.2 on 2024-06-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0084_remove_asignacionactivo_devuelto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='lastname',
        ),
        migrations.AddField(
            model_name='work',
            name='contraseña',
            field=models.CharField(default='contraseña123', max_length=100),
        ),
        migrations.AddField(
            model_name='work',
            name='correo',
            field=models.EmailField(default='correo@ejemplo.com', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='name',
            field=models.CharField(default='Nombre por defecto', max_length=30),
        ),
    ]
