# Generated by Django 4.2 on 2024-06-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0085_remove_work_lastname_work_contraseña_work_correo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
