# Generated by Django 4.2 on 2024-06-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0086_work_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
