# Generated by Django 4.2 on 2024-11-12 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0087_work_last_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='UserData',
        ),
    ]
