# Generated by Django 4.2 on 2024-11-12 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0088_rename_user_userdata'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userdata',
            table='UserData',
        ),
    ]
