# Generated by Django 4.2 on 2025-01-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0089_alter_userdata_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actaentrega',
            name='archivo_pdf',
        ),
        migrations.AddField(
            model_name='actaentrega',
            name='archivo_word',
            field=models.FileField(blank=True, null=True, upload_to='actas_entrega'),
        ),
    ]
